### ISSUE TITLE
recreates removed json files when setting channel and errors

### ISSUE THREAD

**Issue by Storm-Cloud** [toyhippogriff/TwitchKillsStreamers#1]
I don't even know how this is happening

I made a creeper spawn command, I tried to set my channel, it errored, the stack trace mentioned serialising a creeper... the json was now empty, to I removed it, reloaded the commands and tried again, and then it remade the empty creeper.json file... and errored again....

**Comment by Storm-Cloud** [comment]
> Couldn't process command: ttv channel chakatstormcloud
> java.lang.AssertionError: java.lang.NoSuchFieldException: EC_REALLY_ALL
> 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808)
> 	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834)
> 	at com.google.gson.Gson.getAdapter(Gson.java:423)
> 	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
> 	at com.google.gson.Gson.getAdapter(Gson.java:423)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
> 	at com.google.gson.Gson.getAdapter(Gson.java:423)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
> 	at com.google.gson.Gson.getAdapter(Gson.java:423)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
> 	at com.google.gson.Gson.getAdapter(Gson.java:423)
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
> 	at com.google.gson.Gson.toJson(Gson.java:669)
> 	at com.google.gson.Gson.toJsonTree(Gson.java:562)
> 	at com.google.gson.Gson.toJsonTree(Gson.java:541)
> 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
> 	at toyhippogriff.twitchkillsstreamers.command.twitch.TwitchCommand$Serializer.lambda$serialize$1(TwitchCommand.java:84)
> 	at toyhippogriff.twitchkillsstreamers.command.twitch.TwitchCommand$Serializer$$Lambda$5787/464727100.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at toyhippogriff.twitchkillsstreamers.command.twitch.TwitchCommand$Serializer.serialize(TwitchCommand.java:84)
> 	at toyhippogriff.twitchkillsstreamers.command.twitch.TwitchCommand$Serializer.serialize(TwitchCommand.java:54)
> 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
> 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)
> 	at com.google.gson.Gson.toJson(Gson.java:669)
> 	at com.google.gson.Gson.toJson(Gson.java:648)
> 	at com.google.gson.Gson.toJson(Gson.java:623)
> 	at toyhippogriff.twitchkillsstreamers.config.ConfigurationManager.lambda$save$2(ConfigurationManager.java:238)
> 	at toyhippogriff.twitchkillsstreamers.config.ConfigurationManager$$Lambda$5785/35782727.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at toyhippogriff.twitchkillsstreamers.config.ConfigurationManager.save(ConfigurationManager.java:230)
> 	at toyhippogriff.twitchkillsstreamers.config.ConfigurationManager.setChannel(ConfigurationManager.java:110)
> 	at toyhippogriff.twitchkillsstreamers.command.CommandTTV.func_184881_a(CommandTTV.java:69)
> 	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:83)
> 	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119)
> 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91)
> 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962)
> 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941)
> 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
> 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoSuchFieldException: EC_REALLY_ALL
> 	at java.lang.Class.getField(Class.java:1703)
> 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797)
> 	... 55 more
